[경북대 Android_권성찬] 4주차 과제_Step1
kakao-tech-campus-2nd-step2/android-map-location pull request #32
Opened 2024-07-16 10:03 UTC by ksc1008

## 코드를 작성하면서 어려웠던 점
- 카카오 맵 API를 처음 이용하다 보니 배워야 할 새로운 기능들이 많았습니다.
- 자체적인 생명주기를 가지고 있는 카카오 맵과 액티비티의 생명주기를 공유하는 뷰모델 간 데이터 바인딩 중 많은 에러가 발생했습니다.

##중점적으로 리뷰해주셨으면 하는 부분
- 뷰 모델이 굉장이 비대해졌습니다. MVVM에서 뷰모델의 경우 액티비티 당 하나만 바인딩하는게 원칙인 것 같은데, 지금처럼 액티비티의 각 프래그먼트에서 담당하는 기능들을 모두 하나의 뷰 모델에서 구현하는게 맞는 방향인지 궁금합니다.
 - 카메라를 움직일 때마다 sharedPreference로 데이터를 저장하게 구현하였습니다. 핸들링할 수 없는 크래시 상황에서도 데이터가 동기화되게끔 하는게 목적이었는데, 최적화를 생각한다면 앱을 종료할 때 저장하는게 더 맞을지 궁금합니다.

2024-07-19 11:14 UTC, mkSpace commented
리베이스 우선 부탁드립니다

2024-07-19 11:34 UTC, ksc1008 commented
리베이스 완료했습니다!

> 리베이스 우선 부탁드립니다

2024-07-20 06:29 UTC, mkSpace requested changes
이번주도 수고하셨습니다.

SharedPreferences를 본격적으로 사용하면서 난해한 부분도 있을 것 같아요.

SharedPreferences를 사용할 때 생각해보면 좋을 점들 위주로 올려드립니다.

리뷰 읽어보시고 의견 남겨주세요 ~

2024-07-20 06:29 UTC, mkSpace commented on app/src/main/java/ksc/campus/tech/kakao/map/models/MapViewRepository.kt
> +    private fun getZoomCameraPosition(latitude: Double, longitude: Double) = CameraPosition.from(latitude, longitude, 18, 0.0,0.0, -1.0)
상수 잘 빼고 계신데 18, 0.0 등 초기값도 상수로 따로 빼면 의미가 명확해지겠네요.

2024-07-20 06:29 UTC, mkSpace commented on app/src/main/java/ksc/campus/tech/kakao/map/models/MapViewRepository.kt
> +        val sharedPreference = context.getSharedPreferences(CURRENT_POSITION_PREFERENCE_NAME, Context.MODE_PRIVATE)
우선 SharedPreferences를 사용하기 좋은 곳에 사용하신 점 좋습니다!
다만, 생각해 볼 필요가 있는 부분은 SharedPreferences에 CameraPosition를 저장하는 방법에 CameraPosition을 직렬화/역직렬화 해서 넣거나 현재 사용하시는 방식대로 CameraPosition의 각 필드를 하나하나 쪼개서 각 개별의 KEY를 갖도록 구현하는 두 가지 방식이 있을 수 있는데 현재 방식을 사용하신 이유가 있으신가요?

2024-07-20 06:29 UTC, mkSpace commented on app/src/main/java/ksc/campus/tech/kakao/map/models/MapViewRepository.kt
> +        val sharedPreference = context.getSharedPreferences(SELECTED_LOCATION_PREFERENCE_NAME, Context.MODE_PRIVATE)
저는 SharedPreferences를 사용할 때 개별의 클래스로 따로 빼서 작성을 합니다. 그 이유는 SharedPreferences에 데이터를 저장하는 방식은 MapViewRepository 등 (외부 caller)이 모르는게 좋다 라고 생각하는 부분이 있습니다. 현재 MapViewRepository 코드에서는 SharedPreferences의 동작법은 몰라도 좋을거라는 생각이 드네요. 한번 분리해보시겠어요? (필수 사항은 아닙니다)

2024-07-20 06:29 UTC, mkSpace commented on app/src/main/java/ksc/campus/tech/kakao/map/models/MapViewRepository.kt
> +        val sharedPreferences =
현재 SharedPreferences를 서로 다른 이름 SELECTED_LOCATION_PREFERENCE_NAME, CURRENT_POSITION_PREFERENCE_NAME 등으로 분리해서 접근하고 계신데 그 이유가 있을까요?

2024-07-20 06:29 UTC, mkSpace commented on app/src/main/java/ksc/campus/tech/kakao/map/models/MapViewRepository.kt
> +        if (!sharedPreferences.contains(SELECTED_LOCATION_KEY_ADDRESS)) {
객체 인스턴스의 값을 한번에 직렬화를 통해서 저장하고 역직렬화를 통해 불러오며 SharedPreferences 조작하는 객체를 따로 분리하는 이유가 이런거에요. SharedPreferences의 관심사라고 할 수 있는 객체의 저장 및 로드 그리고 현재 상황과 같은 어떤 키가 있어야 데이터가 무결성을 갖는지 등을 MapViewRepsoitory는 몰라야 합니다. 지금 단계에서 고려하기에는 힘들 수 있는데 객체지향 코드를 작성하시면서 항상 각 객체의 관심사 및 책임에 대해 생각해보시고 책임이 과하다 생각드시면 분리하는게 좋을 수 있습니다.

2024-07-20 06:29 UTC, mkSpace commented on app/src/main/java/ksc/campus/tech/kakao/map/models/MapViewRepository.kt
> +    }
위치가 좀 변경되어야 할 것 같네요. 아이템 발행 후 저장이 아닌 저장 후 발행으로 변경해주세요.
이런걸 자동화 하기 위해서 SharedPreferences는 콜백 메서드를 제공합니다.
`sharedPreference.registerOnSharedPreferenceChangeListener` 이 콜백 메서드를 활용해 보세요!

2024-07-20 06:29 UTC, mkSpace commented on app/src/main/java/ksc/campus/tech/kakao/map/models/SearchKakaoHelper.kt
> +        }
이걸 위로 올리는게 더 깔끔하겠네요.
`if(retrofitService == null) { Log 이후 return`

2024-07-20 06:29 UTC, mkSpace commented on app/src/main/java/ksc/campus/tech/kakao/map/views/KakaoMapFragment.kt
> +    }
kakaoMap은 이미 멤버변수인데 이걸 인자로 받을 이유가 있을까요?

2024-07-20 06:29 UTC, mkSpace commented on app/src/main/java/ksc/campus/tech/kakao/map/views/KakaoMapFragment.kt
> +        moveCamera(kakaoMap, viewModel.cameraPosition.value?:MapViewRepository.initialCameraPosition)
viewModel의 cameraPosition 이 세팅 되지 않았을 때 초기값을 주는 것 까지 ViewModel의 역할입니다.
View는 최대한 멍청하게! 비즈니스 로직에 대한 판단이 있으면 안됩니다!

2024-07-20 06:29 UTC, mkSpace commented on app/src/main/java/ksc/campus/tech/kakao/map/views/KakaoMapFragment.kt
> +    private fun changedSelectedPosition(coordinate: LatLng){
```suggestion
    private fun changeSelectedPosition(coordinate: LatLng){
```
과거형보다는 평서문이 컨벤션에 더 맞겠네요

2024-07-20 11:42 UTC, ksc1008 commented on app/src/main/java/ksc/campus/tech/kakao/map/models/MapViewRepository.kt
> +        val sharedPreference = context.getSharedPreferences(CURRENT_POSITION_PREFERENCE_NAME, Context.MODE_PRIVATE)
SharedPreference를 로컬에서 동작하는 DB의 대용 정로도 생각하고 있었습니다.

DB에 데이터를 insert할 때 문자열로 직렬화해서 넣지 않듯, SharedPreference에 값을 넣을 때에도 각 필드에 대한 값을 따로 넣는 방식으로 수행하였습니다.

또한 앱 특성상 데이터의 갱신이 잦은 만큼 string으로 직렬화, 역직렬화 하는 과정에서 오는 오버헤드도 고려하면, 성능 상 이점이 있는 방식을 사용하는게 옳다고 판단했습니다.

2024-07-20 11:42 UTC, ksc1008 commented on app/src/main/java/ksc/campus/tech/kakao/map/models/MapViewRepository.kt
> +        val sharedPreferences =
서로 다른 용도로 사용되는 데이터지만. 둘 다 위치에 대한 정보를 담고 있어 혼동할 수도 있다고 생각해서 둘을 다른 테이블에 분리했습니다.

하지만 이젠 객체단위로 직렬화해서 관리하므로, 같은 클래스에서 관리되는 두 객체를 다른 테이블에 넣을 필요는 없을 것 같아요. 같은 테이블로 통합했습니다!

2024-07-20 11:42 UTC, ksc1008 commented on app/src/main/java/ksc/campus/tech/kakao/map/models/MapViewRepository.kt
> +        if (!sharedPreferences.contains(SELECTED_LOCATION_KEY_ADDRESS)) {
> 저는 SharedPreferences를 사용할 때 개별의 클래스로 따로 빼서 작성을 합니다. 그 이유는 SharedPreferences에 데이터를 저장하는 방식은 MapViewRepository 등 (외부 caller)이 모르는게 좋다 라고 생각하는 부분이 있습니다. 현재 MapViewRepository 코드에서는 SharedPreferences의 동작법은 몰라도 좋을거라는 생각이 드네요. 한번 분리해보시겠어요? (필수 사항은 아닙니다)

짚어주신 부분에 대해 깊게 생각해보았습니다.

아직 MVVM과 클린 아키텍처에 대한 이해가 부족해서 레포지토리가 갖는 책임을 너무 확대해서 생각한것 같습니다. 
레포지토리에서는 도메인 레이어에 표출되는 데이터에 대해서만 직접 관리하고, 실제 데이터가 저장되는 I/O와 같은 동작은 데이터 레이어에 속한 DataSource 클래스로 분리하는게 일반적인 방식이더군요!

일단은 MapViewRepository 에서 SharedPreference에 저장하는 부분을 localDataSource 클래스로 분리하였습니다. 

물론 여전히 수정할 부분이 많이 남아있는 것 같아요.
관련한 내용들을 더 공부해보고 차차 개선시켜 나가겠습니다.

2024-07-20 12:02 UTC, ksc1008 commented on app/src/main/java/ksc/campus/tech/kakao/map/models/MapViewRepository.kt
> +    }
저장 후 발행으로 변경하였습니다!

레포지토리 객체를 생성할 때 context를 참조하지 않는데, sharedPreference 리스너는 어느 시점에 등록해야 옳을까요?

2024-07-20 12:04 UTC, ksc1008 commented
변경 사항 반영하여 푸시하였습니다!

2024-07-21 04:01 UTC, mkSpace commented on app/src/main/java/ksc/campus/tech/kakao/map/models/MapViewRepository.kt
> +    }
Application 에서 등록해주세요

2024-07-21 04:02 UTC, mkSpace commented
머지하고 step2 리베이스 해주세요!

2024-07-21 04:02 UTC, mkSpace approved these changes

2024-07-21 05:05 UTC, ksc1008 commented
> 머지하고 step2 리베이스 해주세요!

쓰기 권한이 없어서 저는 머지를 못합니다!

2024-07-23 07:34 UTC, merged