step1
kakao-tech-campus-2nd-step2/android-map-location pull request #37
Opened 2024-07-16 16:45 UTC by aengzu

2024-07-16 17:22 UTC, aengzu reviewed
파일을 따로 제작하여 맵 레이아웃에 include 로 넣으려 했으나 behavior 적용이 안되어, 이 부분은 맵 뷰에 합치고, 해당 파일은 삭제하였습니다.

2024-07-17 16:09 UTC, InyoungAum requested changes
전반적으로 잘 작성해주셨습니다 고민을 한 흔적이 많이 보이네요 고생하셨습니다!

2024-07-17 16:09 UTC, InyoungAum commented on app/src/main/java/campus/tech/kakao/map/presentation/MapActivity.kt
> +        place = intent.getSerializableExtra("place") as? PlaceVO ?: place
이 코드로 인해서 View(Activity) 에서 Model을  알게되고 접근하게 되는 문제가 생기는데요 
이를 막기 위해선 mapViewModel.getLastPlace()가 VM에 있는 LiveData를 업데이트하고 
intent를 통해 받은 PlaceVO도 VM에서 처리하도록 하는것이 좋을 것 같습니다. 

liveData의 값에 따라 map의 세팅을 다르게하면 mapView를 start하는 코드도 하나로 합쳐질 수 있을 것 같네요!

2024-07-17 16:09 UTC, InyoungAum commented on app/src/main/java/campus/tech/kakao/map/presentation/MapActivity.kt
> +        cameraPositionBuilder.setZoomLevel(21)
nit: 개인취향이긴 하지만 apply로 묶을 수 있는것들을 묶어서 한 뎁스 안쪽으로 보이게 하면 가독성면에서 도움이 됩니다.
```
val cameraPositionBuilder = CameraPosition.Builder().apply{
        setPosition(LatLng.from(latitude, longitude))
        setZoomLevel(21)
}
```

2024-07-17 16:09 UTC, InyoungAum commented on app/src/main/java/campus/tech/kakao/map/presentation/MapActivity.kt
> +        runOnUiThread {
혹시 sleep 을 건 이유가 따로 있을까요?

2024-07-17 16:09 UTC, InyoungAum commented on app/src/main/java/campus/tech/kakao/map/presentation/MapActivity.kt
> +        var styles = LabelStyles.from(
엄격히 따지면 이 친구들도 모델이긴 하지만
비즈니스 로직과 관련이 없기 때문에 저는 View에서 이렇게 처리해도 무방하다고 봅니다. 

다만 LatLng class가 두번 생성 되고 있는데 추가적으로 다른 작업이 있을수도 있으니 이것 자체는 livedata로 뺴는게 더 나을 수도 있겠다는 생각이 드네요

2024-07-17 16:21 UTC, InyoungAum commented
Repository는 보통 관심사에 따라 분리합니다. 유저, 검색, 지도 등등.. 
그런데 검색에서 유저검색이 있을수도 있고 지도를 검색 할 수도 있고 유저가 지도를 저장할 수 도 있고 경우의 수가 굉장히 많습니다. 
레포지토리는 DataSource(내부/외부)와 통신하기 위한 용도이므로 EndPoint기반으로 나누는 경우가 많습니다. 

일단 저 정도로 생각해 두시고 우리가 한 과제를 보면 
searchPlaces (remoteDataSource) : 외부에서 지도를 검색해서 가져옴 
saveSearchQuery (localDataSource) : 외부검색을 한 검색어를 저장함 
getSearchHistory (localDataSource) : 검색어 저장한 목록을 가져옴
removeSearchQuery (localDataSource) : 저장된 검색어 중 일부를 제거 
saveLastPlace (localDataSource) : searchPlaces가 성공했다면 위치를 저장
getLastPlace  (localDataSource) : 저장된 위치가 있다면 가져옴 

이렇게 볼 수 있는데요 각 기능들이 지도 검색 및 표시라는 하나의 피쳐에 묶여있어서 하나의 레포지토리로 가져가도 무방하다고 생각합니다. 
다만 이후에 최근에 검색한 목록만을 따로 빼서보거나 혹은 이와 유사한 가능들이 계속 늘어나게 된다면 Repository를 용도에 따라 분리를 해야 할 수도 있습니다.

2024-07-17 16:23 UTC, InyoungAum commented
(맵 액티비티)->(맵 액티비티 finish 하고 에러 액티비티로 전환)-> (에러 액티비티 finish 하고 맵 액티비티로 재전환)

엑티비티로 error화면을 띄우는 경우는 보통 앱을 종료해야 하거나 재시작 해야할 때 사용합니다. 

단순 이전화면에서 재시도를 한다면 엑티비티를 띄운다기보단 뷰나 dialog등으로 처리하는게 좋을 것 같습니다.

2024-07-18 04:42 UTC, aengzu commented on app/src/main/java/campus/tech/kakao/map/presentation/MapActivity.kt
> +        runOnUiThread {
apiKey 를 빼고 테스트를 했더니 어플을 실행하자마자 너무 바로 해당 화면으로 이동하길래 테스트를 위해 지연을 줬습니다. 삭제하는 걸 까먹었습니다..

2024-07-18 04:43 UTC, aengzu commented on app/src/main/java/campus/tech/kakao/map/presentation/MapActivity.kt
> +        place = intent.getSerializableExtra("place") as? PlaceVO ?: place
넵 저 부분을 어떻게 해야하나 고민이 많았는데 그렇게 하면 되는 군요. 반영하겠습니다. 감사합니다!

2024-07-18 04:43 UTC, aengzu commented on app/src/main/java/campus/tech/kakao/map/presentation/MapActivity.kt
> +        cameraPositionBuilder.setZoomLevel(21)
감사합니다.

2024-07-18 04:44 UTC, aengzu commented on app/src/main/java/campus/tech/kakao/map/presentation/MapActivity.kt
> +        var styles = LabelStyles.from(
넵! 감사합니다.

2024-07-18 11:10 UTC, aengzu commented
- 피드백 반영했습니다!

2024-07-18 13:27 UTC, InyoungAum commented
수고하셨습니다!

2024-07-18 13:27 UTC, merged