충남대 Android_김재민 4주차 Step 2 제출
kakao-tech-campus-2nd-step2/android-map-location pull request #44
Opened 2024-07-17 13:45 UTC by Kjamm

몸 컨디션이 좋지 않아 조금 늦게 제출했습니다 죄송합니다.

## 코드 작성하면서 어려웠던 점
- BuildConfig가 인식 될 때가 있고 인식이 안 될 때가 있는데 해결하느라 시간을 조금 소비했습니다.
- 어떻게 구현해야 할 지 몰라, 인터넷, GPT, API 공식 문서 등등 여러가지를 찾아보았지만 명확한 해답을 찾기 어려웠습니다.
- 코드 길이가 길어지니 수정, 추가가 생각보다 어려웠습니다.

## 중점적으로 리뷰해주셨으면 하는 부분
- 인터넷, GPT, 문서등 막 서치하면서 하다보니 코드가 중구난방인 점이 있는 것 같습니다. 코드가 불필요한 부분이나, 중복된 부분등을 알려주시면 좋겠습니다.
- 전체적으로 구현이 잘 되었는지도 궁금합니다.

## 결과 화면
- error
![KakaoTalk_20240717_223019739](https://github.com/user-attachments/assets/0ae0267d-619e-4519-9ae7-ffae9230fb16)

- 실행 화면
https://github.com/user-attachments/assets/c0016f98-96bf-430e-9469-d136f8285b2e

2024-07-17 15:38 UTC, InyoungAum requested changes
지금 map 하위의 package에 Activity, Repo, Model등의 코드가 혼재되어 있는데요 패키지 분리를 통해 각 파일들을 분류해보는 것도 좋을 것 같습니다. 

컨디션이 좋지 않은 와중에 수고 많으셨습니다!

2024-07-17 15:38 UTC, InyoungAum commented on app/src/main/java/campus/tech/kakao/map/MainActivity.kt
> +                labelLayer = kakaoMap.labelManager?.layer!!
kakaoMap.labelManager가 항상 nullable 아님이 보장이 되지 않는다면 if 문으로 null check를 하는게 안전해 보입니다.

2024-07-17 15:38 UTC, InyoungAum commented on app/src/main/java/campus/tech/kakao/map/MainActivity.kt
> +        if (requestCode == SEARCH_REQUEST_CODE && resultCode == Activity.RESULT_OK) {
MVVM Pattern에서 다소 번거롭겠지만  이 로직은 비즈니스 로직이기 때문에 ViewModel에서 처리하고 
결과에 따라 livedata등을 트리거하여 addMaker 동작을 하는게 좋을 것 같습니다. 

이렇게 해야 이후 테스트를 작성함에도 용이 할 수 있습니다.

2024-07-17 15:38 UTC, InyoungAum commented on app/src/main/java/campus/tech/kakao/map/MainActivity.kt
> +    }
데이터를 Repository에서 가져오면 좋을 것 같습니다.

2024-07-17 15:38 UTC, InyoungAum commented on app/src/main/java/campus/tech/kakao/map/MainActivity.kt
> +    companion object {
위의 코드들을 수정하게되면 아래의 상수값들도 따로 분리를 해두는게 좋을 것 같네요

2024-07-18 00:59 UTC, Kjamm commented on app/src/main/java/campus/tech/kakao/map/MainActivity.kt
> +                labelLayer = kakaoMap.labelManager?.layer!!
넵 반영하겠습니다!

2024-07-18 02:16 UTC, Kjamm commented on app/src/main/java/campus/tech/kakao/map/MainActivity.kt
> +        if (requestCode == SEARCH_REQUEST_CODE && resultCode == Activity.RESULT_OK) {
넵 감사합니다!

2024-07-18 02:25 UTC, Kjamm commented on app/src/main/java/campus/tech/kakao/map/MainActivity.kt
> +    companion object {
넵 반영하겠습니다!

2024-07-18 13:34 UTC, InyoungAum commented
수고하셨습니다!

2024-07-18 13:34 UTC, merged