강원대_Android_김동한_4주차과제_Step1
kakao-tech-campus-2nd-step2/android-map-location pull request #50
Opened 2024-07-18 04:09 UTC by Han961004

맞게 한 건지 잘 모르겠습니다만,
궁금한게 있다면 추후 댓글로 가능할까요?

2024-07-20 04:53 UTC, kold-brewed commented
> 궁금한게 있다면 추후 댓글로 가능할까요?
@Han961004 네~ @kold-brewed 멘션주시고 남겨주시면 확인해볼게요

2024-07-20 06:55 UTC, kold-brewed requested changes
1단계 기능 요구사항에 맞게 잘 작성해주셨네요! BottomSheetBehavior에 대해서도 조금 더 알아두시면 좋을 것 같아요. 고생하셨습니다.

2024-07-20 06:55 UTC, kold-brewed commented on app/src/main/java/campus/tech/kakao/map/view/MainActivity.kt
> +        binding.bottomSheetDescription.text = addressName
이번주 과제 요구사항에는 `BottomSheet`를 사용해야 한다는 내용이 있었습니다.
BottomSheetBehavior의 `STATE_COLLAPSED` 상태를 이용해 하단의 장소정보를 띄워보는 것도 시도해보시면 좋을 것 같아요.

🔗 BottomSheetBehavior https://developer.android.com/reference/com/google/android/material/bottomsheet/BottomSheetBehavior

2024-07-20 06:55 UTC, kold-brewed commented on app/src/main/java/campus/tech/kakao/map/view/MainActivity.kt
> +            sharedPreferences.getString(EXTRA_PLACE_ADDRESSNAME, "Unknown Address").toString()
SharedPreferences도 DB와 같이 모델의 역할을 수행합니다. SearchActivity와 같은 디자인 패턴을 유지하도록 수정해주시면 좋을 것 같아요.

2024-07-20 06:55 UTC, kold-brewed commented on app/src/main/java/campus/tech/kakao/map/view/MainActivity.kt
> +        kakaoMap.labelManager!!.layer!!.addLabel(
`not-null assertion operator(!!)`는 만에 하나라도 labelManager가 null이 되는 순간 예외발생으로 인해 앱이 죽게됩니다. 아래와 같이 non-null임을 100% 확신할 수 있는 상황에서는 괜찮습니다만, 확신할 수 없는 상황이라면 `safe call(?)`을 이용하거나, !!을 쓰되 try-catch로 예외처리를 해주시는 것이 좋습니다.

```kotlin
private var label: Label? = null 
if (label != null) { 
     label!!.layer  
}
```

2024-07-20 06:55 UTC, kold-brewed commented on app/src/main/java/campus/tech/kakao/map/view/MainActivity.kt
> +            sharedPreferences.getString(EXTRA_PLACE_LATITUDE, "37.402005")?.toDouble() ?: 0.0
>  * @throws NumberFormatException if the string is not a valid representation of a number.

toDouble() 역시 예외를 던지는 함수입니다. 직접 예외처리를 해주시거나 혹은 내부에서 예외처리 후 null로 반환해주는 toDoubleOrNull()을 이용하시는 방법도 있습니다.

안드로이드 개발에 있어 예외처리는 굉장히 중요합니다. 생각하지 못한 부분에서 발생하는 예외들을 놓치면 사용자들이 중요한 화면에 진입조차 하지 못하는 경우들이 생기기 때문입니다. 지금은 과제 요구사항에 맞춰 기능을 구현하는 것이 우선이긴 하지만, SharedPreferences는 현업에서 반드시 마주치는 기능이니 이 부분도 꼭 알아두시길 바라요.

2024-07-20 06:55 UTC, kold-brewed commented on app/src/main/java/campus/tech/kakao/map/viewmodel/PlaceAdapter.kt
> +                context.startActivity(intent)
NEW_TASK와 CLEAR_TASK를 함께 사용하면 결국 SearchActivity가 종료되면서 MainActivity로 되돌아갈거예요. 그냥 바로 finish()를 호출하는 것과 동일한 결과가 될 것 같은데, flags로 호출하신 이유가 있으실까요?

2024-07-20 06:55 UTC, kold-brewed commented on app/src/main/java/campus/tech/kakao/map/viewmodel/PlaceAdapter.kt
> +                editor.apply()
onItemClick을 파라미터로 넘겨받는 것의 장점 중에는 클릭이벤트 처리가 수정되어도 PlaceAdapter 클래스를 건드릴 필요가 없다는 점이 있습니다. 또 SharedPreferences와의 데이터 흐름이 하나로 모일 수 있게 ViewModel을 통해 데이터를 넘기는 것이 좋을 것 같구요.

```kotlin
placeAdapter = PlaceAdapter(this, emptyList()) { place ->
            viewModel.addSavedQuery(place.placeName)
            viewModel.최근위치를로컬에저장하는함수(place)
            그리고 화면 전환동작
}
```

2024-07-20 06:55 UTC, merged

2024-07-21 04:58 UTC, kold-brewed commented on app/src/main/java/campus/tech/kakao/map/view/SearchActivity.kt
@Han961004 
`private val viewModel: PlaceViewModel by viewModels { PlaceViewModelFactory(this) }`

ViewModel에 context를 넘기는 건 지양해야 합니다.
Repository 패턴을 학습하시고, SharedPreferences를 품은 모델 역할의 클래스가 ViewModel로 주입되는 형태로 고민해주세요.

2024-07-24 06:01 UTC, Han961004 commented on app/src/main/java/campus/tech/kakao/map/viewmodel/PlaceAdapter.kt
> +                context.startActivity(intent)
처음엔 아래 방법 finish( ) 으로 했는데 [feat : intent 방법 setting] , 다른 방법도 있다고 해서 (위 방법) 하고 잊은 것 같습니다. 


```
class ViewHolder(private val binding: ItemPlaceBinding) : RecyclerView.ViewHolder(binding.root) {
  fun bind(document: Document, onItemClick: (Document) -> Unit) {
      binding.placeName.text = document.placeName
      binding.placeLocation.text = document.addressName
      binding.root.setOnClickListener { onItemClick(document) }
      binding.root.setOnClickListener {
          onItemClick(document)
          val intent = Intent()
          intent.putExtra(MainActivity.EXTRA_PLACE_LONGITUDE, document.x)
          intent.putExtra(MainActivity.EXTRA_PLACE_LATITUDE, document.y)
          (binding.root.context as Activity).setResult(Activity.RESULT_OK, intent)
          (binding.root.context as Activity).finish()
      }
   }
}
```

2024-07-24 15:03 UTC, kold-brewed commented on app/src/main/java/campus/tech/kakao/map/viewmodel/PlaceAdapter.kt
> +                context.startActivity(intent)
@Han961004 
그렇군요! 특별히 동선 상에 문제가 없다면 finish 형태로 작성해주시는게 가장 이해하기 쉬우면서도 일반적인 형태이긴 합니다. (Step2과정에 스킴을 다루는 것 같지는 않습니다만) flag는 보통 해당 Activity로 바로 이동할 수 있는 [스킴](https://developer.android.com/training/app-links/deep-linking)이 있는 경우에 이 스킴을 여러번 호출하면 Activity의 동작은 어떻게 할지 정리하기 위해 사용합니다.