충남대 Android_정기주 4주차 Step1
kakao-tech-campus-2nd-step2/android-map-location pull request #53
Opened 2024-07-18 06:21 UTC by ddangcong80

## 어려웠던 점
- ui 관련한 로직이 많다고 생각해서 정돈이 어려워 코드를 잘 나누지 못하고 mainactivity에 코드를 다 작성하게 된 것 같습니다.
- 카카오 로컬 api 보다 사용법이 어려워 작성된 문서나 샘플코드를 참고하여 작성하는데 시간을 많이 사용했습니다.

## 중점적으로 리뷰해주셨으면 하는 부분
- 필요한 기능들을 함수 단위로 적적히 나눴는지 궁금합니다.
- 앱 종료 시에 마지막 위치를 저장하고 재 실행시 위치를 불러오는 로직이 적절히 구현됐는지 궁금합니다.

2024-07-18 13:33 UTC, InyoungAum requested changes
고생하셨습니다!

2024-07-18 13:33 UTC, InyoungAum commented on app/src/main/java/campus/tech/kakao/map/view/MapActivity.kt
> +        }
이 로직은 데이터 로직이기 때문에 viewModel에서 처리해서 livedata로 넘겨주는게 좋을 것 같습니다.

2024-07-18 13:33 UTC, InyoungAum commented on app/src/main/java/campus/tech/kakao/map/view/MapActivity.kt
> +    private lateinit var spf: SharedPreferences
sharedPreferences + 관련 로직은 repo로 빠지면 좋을 것 같습니다.

2024-07-18 13:33 UTC, InyoungAum commented on app/src/main/java/campus/tech/kakao/map/view/MapActivity.kt
> +    private lateinit var pos: LatLng
이건 viewModel에서 들고있으면 좋을 것 같네요

2024-07-18 13:33 UTC, InyoungAum commented on app/src/main/java/campus/tech/kakao/map/view/MapActivity.kt
> +    private lateinit var KAKAO_APP_KEY: String
API키가 view에 꼭 선언이 되어있어야 할까요?

2024-07-18 13:33 UTC, InyoungAum commented on app/src/main/java/campus/tech/kakao/map/view/MapActivity.kt
> +    private lateinit var retryButton: Button
error 관련 뷰들을 customView로 분리하여 만드는것을 고려해보면 좋겠습니다. 
MapActivity가 알아야 할 view가 너무 많은 것 같네요

2024-07-18 13:33 UTC, InyoungAum commented on app/src/main/java/campus/tech/kakao/map/view/MapActivity.kt
> +            editor.apply()
이로직이 repo에서 이루어지면 좋겠네요

2024-07-19 06:19 UTC, ddangcong80 commented on app/src/main/java/campus/tech/kakao/map/view/MapActivity.kt
> +    private lateinit var KAKAO_APP_KEY: String
필요 없는데 굳이 선언한 것 같습니다! 수정하겠습니다.

2024-07-19 15:51 UTC, InyoungAum commented
수고하셨습니다!

2024-07-19 15:51 UTC, merged