강원대_Android_이아림_4주차과제_STEP1
kakao-tech-campus-2nd-step2/android-map-location pull request #70
Opened 2024-07-19 07:08 UTC by arieum

2024-07-20 08:28 UTC, mkSpace requested changes
이번주도 수고하셨습니다!

아직 MVVM 아키텍처 사용이 많이 미숙해 보입니다. 더불어 아직 상수 표현이라던가 객체간의 통신에 있어서 미흡한 부분이 있습니다.

옳지 않은 방향의 접근 부분에 대해 리뷰 남겨드렸어요. 깊이 고민해보시고 변경 부탁드립니다.

2024-07-20 08:28 UTC, mkSpace commented on app/src/main/java/campus/tech/kakao/map/MainActivity.kt
> +        mainModel = MainModel(application as MyApplication)
mainModel을 우리가 분리하긴 했지만 ViewModel를 생성하면서 Model를 넣어주느라 의존하고 있네요. 이 부분은 어떻게 해결하는게 좋을까요? 한 번 생각해보시면 좋을 것 같아요. 아마 다음 주차에 해결법을 배우실거에요

2024-07-20 08:28 UTC, mkSpace commented on app/src/main/java/campus/tech/kakao/map/MainActivity.kt
> +        tabRecyclerView = binding.tabRecyclerview
바인딩을 쓰고부터는 View 캐싱을 굳이 하실 필요 없습니다.

2024-07-20 08:28 UTC, mkSpace commented on app/src/main/java/campus/tech/kakao/map/MainActivity.kt
> +                recyclerView.isGone = true
```suggestion
                recyclerView.isVisible = false
```
로 하나만 사용하시는게 가독성엔 더 나아 보입니다! (필수 변경사항은 아닙니다)

2024-07-20 08:28 UTC, mkSpace commented on app/src/main/java/campus/tech/kakao/map/MainActivity.kt
> +            if (list.isEmpty()) {
`placeList가 비었으면 리사이클러뷰를 보여준다 안보여준다` 이 또한 비즈니스 로직이에요. 그래서 mainViewModel에 showPlaceList 등을 따로 만들고 RecyclerView랑 바인딩 해주시는게 제일 좋습니다 :)

2024-07-20 08:28 UTC, mkSpace commented on app/src/main/java/campus/tech/kakao/map/MainActivity.kt
> +        mainViewModel.placeList.observe(this) { list ->
```suggestion
        mainViewModel.showPlaceList.observe(this) { isShow ->
            recyclerView.isVisible = isShow
            noResuleTextView.isVisible = !isShow
        }
```
이렇게 변경하시는게 더 깔끔하겠네요

2024-07-20 08:28 UTC, mkSpace commented on app/src/main/java/campus/tech/kakao/map/MainActivity.kt
> +        input.addTextChangedListener(object : TextWatcher {
이거 확장 함수 중에 필요없는 함수는 구현 안해도 되는 확장함수가 있어요 잘 찾아보세요!

2024-07-20 08:28 UTC, mkSpace commented on app/src/main/java/campus/tech/kakao/map/MainActivity.kt
> +        }
SharedPreferences는 엄밀히 말해 Repository의 역할이 큰 친구죠! db와 같은 역할이에요. 그럼 이 부분이 View에 있어야 할까요? 어디에 위치해야 할 지 생각해 보세요!

2024-07-20 08:28 UTC, mkSpace commented on app/src/main/java/campus/tech/kakao/map/MainActivity.kt
> +    }
필요없는 코드에요

2024-07-20 08:28 UTC, mkSpace commented on app/src/main/java/campus/tech/kakao/map/MainActivity.kt
> +        super.onDestroy()
이 코드도 의미없어 보이네요

2024-07-20 08:28 UTC, mkSpace commented on app/src/main/java/campus/tech/kakao/map/MainModel.kt
> +    }
이건 다른 파일로 분리해주세요.
엄밀히 보면 Service가 항상 하나일 수는 없으니 RetrofitClient, ApiService는 분리되어야 합니다.
제가 듣기로는 다음 주차에 배우게 될 테니 다음주에 변경하셔도 좋습니다

2024-07-20 08:28 UTC, mkSpace commented on app/src/main/java/campus/tech/kakao/map/MainModel.kt
> +    fun callKakao(query: String, callback: (List<Place>) -> Unit){
함수 이름이 함수의 역할을 제대로 설명하진 않는것 같네요. search~~ 등으로 변경하는게 명확해 보입니다.

2024-07-20 08:28 UTC, mkSpace commented on app/src/main/java/campus/tech/kakao/map/MainModel.kt
> +    private var placeList = mutableListOf<Place>()
placeList 캐싱하는건 의미가 없어뵙니다

2024-07-20 08:28 UTC, mkSpace commented on app/src/main/java/campus/tech/kakao/map/MainModel.kt
> +class MainModel(private val application: MyApplication) {
강의에서 Model 네이밍으로 들으셨나요? Repository 느낌이 강하네요.
그리고 MainModel 이 아니라 도메인 이름으로 분리하시는게 좋아요. 현재 여기서는 PlaceRepository 정도가 맞겠네요

2024-07-20 08:28 UTC, mkSpace commented on app/src/main/java/campus/tech/kakao/map/MainModel.kt
> +    fun getResearchLogs() {
get이 맞나요? 반환 값이 없는데용..

2024-07-20 08:28 UTC, mkSpace commented on app/src/main/java/campus/tech/kakao/map/MainModel.kt
> +    fun getResearchLogs() {
getResearchLogs() -> getLogList()
순서가 생겨버렸네요. 이런 프로그래밍 방식은 작성하시면 안돼요! 협업에 매우 어려운 코드입니다.
Observable 패턴을 사용하시는게 가장 베스트이긴 한데 힘드시면 이 함수에서 최신화된 데이터를 바로 넘겨주는게 신뢰성이 더 높습니다.

2024-07-20 08:28 UTC, mkSpace commented on app/src/main/java/campus/tech/kakao/map/MainModel.kt
> +    fun getLogList() = logList
LiveData를 활용해보세요

2024-07-20 08:28 UTC, mkSpace commented on app/src/main/java/campus/tech/kakao/map/MainViewModel.kt
> +            }
안드로이드에서 권장 데이터 흐름은 Remote -> Local -> View 순입니다.
Remote call로 api에서 데이터를 가져온 후 db에 저장 하고 db에서 View로 검색 결과를 전달하는게 SSOT를 DB로 두는 방식이고 권장하는 방식입니다. (시간 남으시면 고쳐보세요 ~)

2024-07-20 08:28 UTC, mkSpace commented on app/src/main/java/campus/tech/kakao/map/MainViewModel.kt
> +    fun callLogList() = mainModel.getLogList()
LiveData 배우셨으니 Observable하게 데이터를 전달해주세요

2024-07-20 08:28 UTC, mkSpace commented on app/src/main/java/campus/tech/kakao/map/MainViewModel.kt
> +    }
네이밍에도 신경 써 주세요 tabRecyclerView를 세팅한다는 View Control 관련 내용은 ViewModel에 있어선 안돼요. 이건 이전에 MVP 패턴에서 Presenter가 하는 역할과 유사합니다. 우리는 MVVM 아키텍처의 ViewModel를 조작하기에 데이터를 조작하는 의미로 네이밍 하셔야 오해의 소지가 없을 것 같네요.
updateTabViewVisible 정도가 좋겠네요.

2024-07-20 08:28 UTC, mkSpace commented on app/src/main/java/campus/tech/kakao/map/MainModel.kt
> +    fun hasAnyClick() : Boolean {
클릭한 기록인가요...? 우리는 데이터를 저장하는거지 사용자 행동을 기록하는게 아닙니다. 네이밍 변경해주세요!

2024-07-20 08:28 UTC, mkSpace commented on app/src/main/java/campus/tech/kakao/map/MainViewModel.kt
> +    }
이건 무슨뜻인가요?

2024-07-20 08:28 UTC, mkSpace commented on app/src/main/java/campus/tech/kakao/map/MainViewModel.kt
> +    fun deleteLogClickListner(item: Place){
함수 body에 리스너를 등록하는 코드가 없는데 함수명은 어떤 의미인가요?

2024-07-20 08:28 UTC, mkSpace commented on app/src/main/java/campus/tech/kakao/map/MainViewModel.kt
> +    fun deleteLogClickListner(item: Place){
이렇게 작성하면 View가 클릭 리스너를 작동한다고 하면 그건 View의 역할이지 MainViewModel은 모릅니다! 알아서도 안되구요! 딱 함수가 하는게 뭔지 잘 살펴보시고 그에 맞게 네이밍 해주세요.

2024-07-20 08:28 UTC, mkSpace commented on app/src/main/java/campus/tech/kakao/map/MapViewActivity.kt
> +                        position = LatLng.from(placeY!!.toDouble(), placeX!!.toDouble())
!! 사용은 지양해주세요! 어떻게 변경할 수 있을까요?

2024-07-20 08:28 UTC, mkSpace commented on app/src/main/java/campus/tech/kakao/map/MapViewActivity.kt
> +                    intent.putExtra("ERROR", errorMsg)
Intent는 액티비티간의 통신이죠? 이 통신방법이 Literal 하게 작성되어선 안됩니다. 상수로 변경해주세요

2024-07-20 08:28 UTC, mkSpace commented on app/src/main/java/campus/tech/kakao/map/MapViewActivity.kt
> +                        val (x, y) =  lastLocation!!
!! 삭제해주세요

2024-07-20 08:28 UTC, mkSpace commented on app/src/main/java/campus/tech/kakao/map/MapViewActivity.kt
> +        val x = sharedPreferences.getString("PLACE_X", "NULL")
null을 "NULL"로 변경하신 이유가 있을까요?
getString 원형을 읽어보시면 nullable도 전달 가능합니다.
getString("PLACE_X", null) 로 해주세요
"NULL" 은 절대 금지입니다! 이건 의미가 없는걸 떠나서 위험한 코드에요

2024-07-20 08:32 UTC, mkSpace commented
더불어서 package 관리가 제대로 안되고 있습니다. MVVM 패키징 관련해서 찾아보시고 학습하신 후 패키지 구조 변경해주세요!

2024-07-20 10:16 UTC, arieum commented on app/src/main/java/campus/tech/kakao/map/MainModel.kt
> +    }
🖋️ Retrofit 필요한 3가지 클래스
- JSON 형태의 Data_Class ⭕
- HTTP 통신에 사용할 Interface ⭕
- Retrofit.Builder를 선언한 Object ⭕ = **RetrofitClient**

🖋️ 헷갈리는 Retrofit 메서드
- `build()` : 구성옵션을 바탕으로 Retrofit 인스턴스 생성
- `create()` : **API 인터페이스의 구현체**를 생성
※ API 인터페이스의 구현체 -> HTTP 요청을 수행하고 응답을 처리하는 데 필요한 모든 메서드를 포함 -> ex. Kakao로컬API에서는 getPlace() 메서드

🖋️ A/S 내용
- RetrofitClient는 일반적으로 싱글톤 패턴을 사용하여 앱 전체에서 동일한 Retrofit 인스턴스를 재사용하도록 한다

2024-07-20 10:28 UTC, arieum commented on app/src/main/java/campus/tech/kakao/map/MainModel.kt
> +    fun callKakao(query: String, callback: (List<Place>) -> Unit){
`callKakao` -> `searchPlaces` 변경!

2024-07-20 11:37 UTC, arieum commented on app/src/main/java/campus/tech/kakao/map/MainViewModel.kt
> +    }
`inputCloseButtonClickListener()` -> `closeButtonClickListner()` 네이밍 변경!

2024-07-20 11:40 UTC, arieum commented on app/src/main/java/campus/tech/kakao/map/MainViewModel.kt
> +    }
💁‍♀️acitivty_main.xml에 closeButton이 두 개(ⓐ 검색창 ⓑ 클릭기록창)가 있어서 구분하려고 썼었는데.. 제가봐도 이름 어이 없는 것 같아요 ..

2024-07-20 14:57 UTC, arieum commented on app/src/main/java/campus/tech/kakao/map/MainActivity.kt
> +            if (list.isEmpty()) {
>`검색어 결과_리스트`에 대한 Livedata -> **_placeList**
> 검색어 결과목록을 보여주는 `Recyclerview의 Visibility`에 대한 Livadata -> **_placeListVisible**

2024-07-20 15:33 UTC, arieum commented on app/src/main/java/campus/tech/kakao/map/MainActivity.kt
> +        mainViewModel.placeList.observe(this) { list ->
⚠️위에서  _placeListVisible을 설정한 이후 마주한 문제⚠️ : `스페이스바`를 눌러야 결과가 나온다
 -> 첫번째 해결책 : addTextChangedListener의` afterTextChanged` 말고 `onTextChanged`에서 로직을 구현하자 -> 해결❌
-> 두번째 해결책 : 확장함수를 이용하자 -> RxBinding의 textChanges() -> 해결 ❌
-> 두번째 해결책 + 응용 : textChanges()의 debounc(300, TimeUnit.MILLISECONDS) 설정 -> 해결 ❌ 
-> 세번째 해결책 : observe의 문제가 아니라 recyclerviewAdapter 문제일 수도 있다. resultAdapter.notifyDataSetChanged() 호출해보자 -> 해결 ❌

2024-07-20 16:19 UTC, arieum commented on app/src/main/java/campus/tech/kakao/map/MainModel.kt
> +    fun getLogList() = logList
?!? Model에서도 LiveData를 써도 되나요 ?!? ViewModel에서만 사용하는 거 아니었나요 ?!?
![PedroMonkeyPuppetGIF](https://github.com/user-attachments/assets/78e47918-8960-4716-83fd-b96492bccd31)

2024-07-20 16:27 UTC, arieum commented on app/src/main/java/campus/tech/kakao/map/MainActivity.kt
> +        input.addTextChangedListener(object : TextWatcher {
RxBinding의 textChanges() 사용!

2024-07-20 16:33 UTC, arieum commented on app/src/main/java/campus/tech/kakao/map/MainViewModel.kt
> +    fun deleteLogClickListner(item: Place){
deleteLogClickListner() -> deleteLogEntry() 변경!

2024-07-20 17:24 UTC, arieum commented on app/src/main/java/campus/tech/kakao/map/MainModel.kt
> +    fun getLogList() = logList
"`이 작업은 일반적으로 ViewModel 클래스 내에서 이루어집니다.`" 이건 그냥 권장인건가요?!
![image](https://github.com/user-attachments/assets/de000a90-fbda-4b94-b9c6-a224947a73a2)

2024-07-20 19:34 UTC, arieum commented
- 코드수정이후 몇몇 검색어의 경우 스페이스바까지 눌러야 검색결과가 나오는 예외상황들이 생겼습니다. (5번째 코멘트에 제가 시도한 해결방법들 적어놨습니다!) 동기처리도 해봐야 해결될 것 같습니다..! 실행할 때 혹시라도 결과가 안나온다면 스페이스바까지 눌러주세요!!🙇‍♀️🙇‍♀️  

https://github.com/user-attachments/assets/3d3a5975-3f37-4307-bac0-14d0195d4724

2024-07-20 19:54 UTC, arieum commented
하찮지만 UI Test 커밋도 있습니다 .. ! 단위테스트랑 Mock 구현은 아직 못했습니다 ..😢

2024-07-22 08:27 UTC, mkSpace commented on app/src/main/java/campus/tech/kakao/map/MainActivity.kt
> +        input.addTextChangedListener(object : TextWatcher {
TextView 확장함수 중 addTextChangedListener 같은 이름의 확장함수가 있어요!

2024-07-22 08:30 UTC, mkSpace commented on app/src/main/java/campus/tech/kakao/map/MainModel.kt
> +    fun getLogList() = logList
지금 최신 데이터를 가지고 오실 때 순서가 생기는 방향으로 작성하셔서 Observable 패턴을 도입하면 좋을 것 같아서 말씀드린거였어요 Rx나 Coroutine을 써야 하는데 아직 배운 부분이 아니다 보니.. 우선 이 부분은 넘어가시죠

2024-07-22 08:31 UTC, mkSpace commented on app/src/main/java/campus/tech/kakao/map/MainViewModel.kt
> +    }
노노노 MainViewModel의 특정 로직으로 인해 View가 어떻게 변경되는지는 ViewModel의 관심사가 아니에요! Button, Click, Listener 모두 알 필요 없어야 합니다. 다르게 네이밍 해주세요. clearPlaceList 이런식으루요

2024-07-22 09:54 UTC, mkSpace commented
`마지막 위치를 기억해야 한다!` 이 기능을 구현하기 위해 강제 종료되는 시점을 트래킹하는 것은 어려운 일입니다. 특히 언제 어떤 이유로 종료 될 지 모르는 모바일 환경에서 이를 구현하기엔 쉽지 않은데요. 그래서 보통 이런 경우 사용자의 검색이 일어날 때 마다 가장 최신의 값을 업데이트하여 저장해 두는 방식을 많이 사용합니다. 그렇게 구현해보시겠어요?

2024-07-22 11:07 UTC, arieum commented on app/src/main/java/campus/tech/kakao/map/MainModel.kt
> +    fun getLogList() = logList
😢

2024-07-22 11:08 UTC, arieum commented on app/src/main/java/campus/tech/kakao/map/MainViewModel.kt
> +    }
아하! 💡

2024-07-22 11:14 UTC, arieum commented on app/src/main/java/campus/tech/kakao/map/MainActivity.kt
> +        input.addTextChangedListener(object : TextWatcher {
doOnTextChanged 😊!!

2024-07-22 11:15 UTC, arieum commented on app/src/main/java/campus/tech/kakao/map/MainModel.kt
> +    fun getLogList() = logList
😭😭😭

2024-07-22 18:09 UTC, arieum commented
⚠️ 스페이스바 이슈 해결
![image](https://github.com/user-attachments/assets/56b6d9c5-d0a2-41e7-8e17-6b3e64132e28)
아직 직전 피드백에 대해서 답장을 받지 못해 섣불리 피드백하지 않은 내용에 대한 수정사항을 push 하지는 못했습니다..!
이렇게 해결해도 될까요?

2024-07-23 06:53 UTC, mkSpace commented
> ⚠️ 스페이스바 이슈 해결 ![image](https://private-user-images.githubusercontent.com/143606293/351067391-56b6d9c5-d0a2-41e7-8e17-6b3e64132e28.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3MTcyNDksIm5iZiI6MTcyMTcxNjk0OSwicGF0aCI6Ii8xNDM2MDYyOTMvMzUxMDY3MzkxLTU2YjZkOWM1LWQwYTItNDFlNy04ZTE3LTZiM2U2NDEzMmUyOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyM1QwNjQyMjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZWY0YjQ5OWExMDdmNThmYzEyNmI2MDY2YWU5NGNlOTRkYTE2ZDNmYzAyMTRkZTA4MmJkYzgwMGQwOGE5ZDJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xxEvXPqBmPD2UmDcEjLqGLLtl-vhwbtXNoC7YpXNVp8) 아직 직전 피드백에 대해서 답장을 받지 못해 섣불리 피드백받지 않은 내용에 대한 수정사항을 push 하지는 못했습니다..! 이렇게 해결해도 될까요?

아림님 스페이스 문제는 그 문제가 아닙니다.

PlaceRepository에 search하고 Retrofit Call 을 통해 통신을 하고 계신데 이것은 비동기 태스크여서 언제 완료될지 모르는 상태에요. 그런데 MainViewModel에 비동기 태스크를 호출하고 바로 placeList를 불러오면 검색 api를 통해 내려받은 데이터가 포함된 상태의 placeList를 반환받는게 아닌 이전 상태(검색 api 반영 전)의 placeList를 내려받기에 변화가 없는겁니다.
스페이스 바가 문제가 아니라 다른 어떠한 문자를 넣으셔도 그 이전의 입력값을 기준으로 검색 api를 통해 내려받아 캐싱한 placeList를 반환 받으실겁니다.
그래서 이 문제를 해결하기 위해 Observable 패턴을 사용하는거에요. 비동기 태스크가 언제 끝날 지 모르니 비동기 태스크 끝난 이후 upstream 에서 새로운 item을 offer를 하게 해서 observe 하는 곳(View)에서 비동기 태스크 끝난 후의 최신의 데이터를 전달 받을 수 있게 설계하는것입니다.
다만 Coroutine이나 Rx를 사용하지 않는 상태에서 최신의 값을 받기 위해서는 콜백을 사용하거나 여의치 않으니 LiveData 정도로 구현해보라고 말씀드린겁니다.
아림님이 찾으신대로 LiveData를 사용하기 마땅치 않다고 생각드시면 placeRepository.search~~() 함수 내에서 Retrofit 통신 완료 후 LiveData의 placeList에 값을 전달하는 콜백 메서드를 호출하는 식으로 구현해보세요.

2024-07-24 11:03 UTC, arieum commented
☢️ 이번주 과제 틈틈이 연습하느라 갑작스럽게 `interface 추가`, `hilt 적용`, `room 적용` 변경사항이 있습니다. 이건 무시하셔도 됩니다! 이번주 과제 PR때 피드백 받겠습니다!
☢️ 가독성을 위해서 MainActivity에 각각의 기능을 모두 메서드로 분리했습니다. 
![image](https://github.com/user-attachments/assets/6a4d73ed-e4f1-4945-8bbb-d8b2b1151058)

☢️**검색결과값을 보여주는 기능**과 **클릭한결과를 보여주는 기능**을 나눠놨습니다
![image](https://github.com/user-attachments/assets/487ba408-5bdd-47f4-92e6-1f3716e853ea)

👇여기가 마지막 피드백에 대한 수정사항입니다
### input에 사용자 입력시 호출순서
1. `setupEditTextListeners()` 內 `doAfterTextChanged` 실행 
2. `handleTextChanged()` 內 `placeViewModel.callResultList(*콜백1*전달)` 실행  
3. `placeRepository.searchPlaces(*콜백2*전달)` 실행 
4. 네트워크 처리 실행&성공 
5. *콜백2* 실행 : ① _placeList에 값 전달 ② _placeListVisible 갱신 
6. *콜백1*실행 : ① placeList.observe하여 Recyclerview에 submitList! ② placeListVisible.observe하여 Recyclerview는 보이게, noResultTextVIew는 가림

![image](https://github.com/user-attachments/assets/948733c6-51a5-4ad5-a7c1-a97575e024a0)


![image](https://github.com/user-attachments/assets/2352c646-b17a-4eeb-b5ee-a36282069182)


![image](https://github.com/user-attachments/assets/bf7f8a15-d6a7-4eb7-8a18-6dcffaf36255)

2024-07-24 11:31 UTC, arieum commented
헉스.. 생각해보니 저 room, hilt 변경한 상태로 commit 해버리면 .... 안됐었네요 ..... 🫨 
이건 다시 해결하겠습니다.. ㅠㅠ

2025-10-07 10:52 UTC, closed without merging