전남대 Android_최영빈_4주차 과제_step2
kakao-tech-campus-2nd-step2/android-map-location pull request #80
Opened 2024-07-19 08:36 UTC by yb0x00

### 코드 작성하면서 어려웠던 점
- 어떤 기능을 테스트할 수 있는지 판단이 어려웠습니다.
- 우선으로 이번 주차 과제 내용에 대한 테스트 코드를 작성하고자 하였으나 완료하지 못한 상황입니다.
구글링해도 '인텐트 사용, 액티비티 전환'에 대한 UI 테스트 가능 여부가 모호하게 느껴졌고, 실제 이 부분에 대한 테스트 코드를 고민하였으나 답을 찾지 못했습니다.

### 과제를 하면서 느낀점
- 테스트 코드 작성을 어려워해서 해결을 못 하는 건지, 코드 자체를 테스트 작성이 어렵게 짠 건지 혼란이 오는 순간들이 있었습니다.
- 테스트 코드를 작성하는 것과 코드를 작성하는 것이 별개의 일이 아님을 느껴, 이번 과제를 수행하면 앞으로 코드를 작성할 때 의존성이나 구조 자체를 더 의식할 수 있지 않을까 생각하여 이번 과제를 잘하고 싶었습니다.

### 😢
- 제대로 동작하는 테스트 코드를 작성하지 못해, 현재 'EditText의 text가 의도했던 대로 화면에 나타나는지'만 테스트한 상황입니다.
- 일정에 따라 우선 제출하는 상황으로, 내일(20일. 토) 오후 6시까지는 더 고민해서 최대한 추가로 테스트 코드를 작성하겠습니다.
코치님 바쁘실텐데 일정에 차질을 빚어 정말 죄송합니다!

2024-07-20 08:36 UTC, yb0x00 commented
시간이 더 필요할 것 같습니다 😢
step1 피드백 반영도 최대한 빨리 하겠습니다! 죄송합니다!!

2024-07-21 04:49 UTC, omjoonkim requested changes
영빈님~ 아직 2단계 커밋은 올라오지 않은 것으로 보입니다. 작업이 완료된 이후에 한번더 리뷰를 요청해주세요.

2024-07-21 11:04 UTC, yb0x00 commented
테스트 코드 추가하였습니다!
테스트 코드가 어렵게 느껴지기도 했고, 최근 3일간 건강이 좋지 않아 과제에 집중하지 못했습니다.
정말 죄송합니다!

### 멘토님이 리뷰해주셨으면 하는 부분
테스트 코드를 작성하는 것이 미흡해서 테스트 코드를 작성하는데 어려움이 있었습니다.
추가적으로 작성되면 좋을 테스트가 있을 지 여쭙고 싶습니다.

2024-07-21 14:43 UTC, omjoonkim approved these changes
2단계 과제 진행하시느라 고생하셨습니다~!.
가능하다면 뷰모델에 대한 단위 테스트도 작성해보셔요. :)

2024-07-21 14:43 UTC, omjoonkim commented on app/src/androidTest/java/campus/tech/kakao/map/HomeMapActivityTest.kt
> +    fun 검색바를_클릭하면_검색화면으로_이동() {
HomeMapActivityTest 파일의 전체 테스트를 실행하면 이 테스트에서 에러가 발생합니다. 
각 테스트가 다른 테스트에 영향을 주지 않도록 테스트를 설계하고 버그를 수정해보세요.

2024-07-21 14:43 UTC, omjoonkim commented on app/src/androidTest/java/campus/tech/kakao/map/MapErrorActivityTest.kt
> +    fun 오류내용_보여줌() {
테스트 케이스의 이름만 보고 어떤 동작의 무엇을 검증하는지를 이해할 수 있어야 합니다. 
[링크](https://medium.com/@stefanovskyi/unit-test-naming-conventions-dd9208eadbea)를 참고해서 네이밍을 적절하게 수정해보세요. 한글을 그대로 사용하셔도 무방합니다. :)

2024-07-22 06:00 UTC, yb0x00 commented on app/src/androidTest/java/campus/tech/kakao/map/MapErrorActivityTest.kt
> +    fun 오류내용_보여줌() {
피드백 감사합니다!

`onMapError 예외 설명 에러 화면에 나타남`으로 수정하였습니다.
괜찮은 함수명인지는 아직 모호하게 느껴집니다😅

2024-07-22 06:53 UTC, yb0x00 commented on app/src/androidTest/java/campus/tech/kakao/map/HomeMapActivityTest.kt
> +    fun 검색바를_클릭하면_검색화면으로_이동() {
피드백 감사합니다!
```
@Before
    fun setup() {
        init()
    }

    @After
    fun teardown() {
        release()
    }
```
[문서](https://developer.android.com/reference/androidx/test/espresso/intent/Intents)를 참고하여 인텐트 init()과 release()를 추가하였습니다.

init()와 release()가 필요한 이유는 '당연히 해야 하는 작업이기 때문'이라고 생각해도 될까요?

2024-07-22 13:37 UTC, yb0x00 commented
[step1과](https://github.com/kakao-tech-campus-2nd-step2/android-map-location/pull/45) step2 피드백 반영하였습니다.

2024-07-23 09:01 UTC, yb0x00 commented
@omjoonkim 

> 싱글톤 형태는 사용하기에는 굉장히 편리하지만 추후 관리에 어려움이 생길 수 있어요. MVVM패턴에 맞게 prefs이 사용되는 역할을 가진 컴포넌트를 정의하고, 해당 컴포넌트에서 로직이 수행되도록 코드를 개선해보세요.

- Repository에서 SharedPreference 관련된 작업이 이루어지는 것이 더 바람직한 것 같아 69c19e5d377eb221b655813bfaf8cb2f9f049895 내용을 수정하였습니다.

- ViewModel에 직접 Application Context를 전달하여 사용했던 기존 방식으로 인해 Unit Test 작성이 어려워진 것 같아, ViewModelFactory를 사용하여 Repository를 주입하는 방식으로 수정했습니다.
```
class MapViewModel(application: Application): AndroidViewModel(application){
...
}
```
❗ 수정한 내용이 타당한지, [AndroidViewModel](https://developer.android.com/reference/androidx/lifecycle/AndroidViewModel)을 사용할 수 밖에 없는 상황이 따로 있는지도 궁금합니다!

2024-07-23 12:37 UTC, omjoonkim commented on app/src/androidTest/java/campus/tech/kakao/map/HomeMapActivityTest.kt
> +    fun 검색바를_클릭하면_검색화면으로_이동() {
테스트 환경에 공유 객체 사용이 필요할 경우, 각 테스트를 독립적으로 만들기 위해 적절한 상태관리가 필요합니다. init, release그런 의미에서 사용하신다고 생각하시면 될 것 같아요.

함수명같은 경우 영어 사용을 추천드립니다만, 어떤 조직, 환경에서 일하는가에 따라서 중요도가 달라질 수 있습니다.

2024-07-23 12:38 UTC, omjoonkim commented on app/src/androidTest/java/campus/tech/kakao/map/MapErrorActivityTest.kt
> +    fun 오류내용_보여줌() {
네이밍에 어려움을 느끼실 경우엔 최대한 구체적으로 작성하려고 생각해보세요. ㅎㅎ 
저도 항상 네이밍에 어려움을 느낍니다.

2024-07-23 12:38 UTC, omjoonkim commented
고생하셨습니다~!

2024-07-23 12:38 UTC, merged