전남대 Android_이민서_4주차 과제_Step 2
kakao-tech-campus-2nd-step2/android-map-location pull request #81
Opened 2024-07-19 08:37 UTC by LEEMINSEO00

# 4주차 과제_Step 2
## 위치 이동: 테스트
### 코드 작성하면서 어려웠던 점

### 멘토님이 중점적으로 리뷰해주셨으면 하는 부분

### 실행 결과

아직 완성시키지 못했으나 구글 폼 제출을 위해 먼저 PR합니다.

2024-07-21 04:18 UTC, omjoonkim requested changes
단위 테스트 작성도 요구사항중의 하나입니다. 작성해서 올려주셔요~!

2024-07-21 04:18 UTC, omjoonkim commented on app/src/androidTest/java/campus/tech/kakao/map/MainActivityTest.kt
> +    fun displaySearchResults() {
테스트 케이스의 이름만 보고 어떤 동작의 무엇을 검증하는지를 이해할 수 있어야 합니다. 
[링크](https://medium.com/@stefanovskyi/unit-test-naming-conventions-dd9208eadbea)를 참고해서 네이밍을 적절하게 수정해보세요.

2024-07-21 04:18 UTC, omjoonkim commented on app/src/androidTest/java/campus/tech/kakao/map/MainActivityTest.kt
> +        SystemClock.sleep(1000)
보통 테스트 코드 작성시 Given When Then 형태의 컨벤션을 사용합니다. 
[링크](https://brunch.co.kr/@springboot/292)를 참고하여 코드를 수정해보세요.

2024-07-22 15:10 UTC, LEEMINSEO00 commented on app/src/androidTest/java/campus/tech/kakao/map/MainActivityTest.kt
> +    fun displaySearchResults() {
'When_StateUnderTest_Expect_ExpectedBehavior' 스타일을 택했습니다.

2024-07-22 17:06 UTC, LEEMINSEO00 commented on app/src/androidTest/java/campus/tech/kakao/map/MainActivityTest.kt
> +        SystemClock.sleep(1000)
Given When Then 형태의 컨벤션에 대해 이해는 했으나 수정 방향을 잘 모르겠습니다..

2024-07-23 12:51 UTC, omjoonkim commented on app/src/androidTest/java/campus/tech/kakao/map/MainActivityTest.kt
> +class MainActivityTest {
파일에 대한 테스트를 전체 실행하면 `when_InputSearch_Expect_DisplaySearchResults` 케이스에서 에러가 발생합니다. 
각 테스트는 독립적으로 수행되어야 해요. 공유 객체가 있는지 확인해보고 문제를 해결해보세요.

2024-07-23 12:52 UTC, omjoonkim commented on app/src/androidTest/java/campus/tech/kakao/map/MainActivityTest.kt
> +        SystemClock.sleep(1000)
에스프레소 문법으로 인해 UI테스트는 이러한 패턴을 사용하기가 어려울 수 있습니다.
한가지 팁을 주자면, Android 라이브러리, 혹은 구글 개발자들의 깃헙 레포에 UI테스트들은 어떻게 작성되어있는지 참고해보세요.

2024-07-23 12:53 UTC, omjoonkim approved these changes
민서님 2단계 과제 진행하시느라 고생하셨습니다. 코멘트는 시간되실때 꼭 확인해보세요~!

2024-07-23 12:53 UTC, merged