전남대 Android_장수민_4주차 과제(4단계)
kakao-tech-campus-2nd-step2/android-map-location pull request #96
Opened 2024-07-20 07:53 UTC by sumintnals

## 2주차 과제

## 1단계
### 기능 사항
-  저장된 검색어를 선택하면 해당 검색어의 검색 결과가 표시된다.
- 검색 결과 목록 중 하나의 항목을 선택하면 해당 항목의 위치를 지도에 표시한다.
- 앱 종료 시 마지막 위치를 저장하여 다시 앱 실행 시 해당 위치로 포커스 한다.
- 카카오지도 onMapError() 호출 시 에러 화면을 보여준다.

## 2단계
### 기능 사항
- 테스트 코드를 작성한다.

가능한 MVVM 아키텍처 패턴을 적용하도록 한다.
---

### ⚠️참고사항
- 기능 구현이 늦어져서 step2 브랜치에서 이어서 작업했습니다(이번 과제가 어려워서 과제를 제출하는 것이 늦어졌습니다... 정말 죄송합니다ㅠㅠㅠㅠㅠㅠㅠ)
#### [1단계 작업](https://github.com/kakao-tech-campus-2nd-step2/android-map-keyword/pull/3)

- 사용자가 앱을 실행하면 마지막에 검색한 장소가 지도에 표시되고,
- 맵 뷰를 한 군데에서만 사용하기 위해서, 바텀 시트의 보이는 기준을 intent로 전달받은 값이 있는지를 기준으로 해서(있으면 바텀 시트에 정보가 보입니다) 서치 액티비티에서 검색 결과를 클릭한 경우 intent에 값을 넣어주어서 지도에 그 검색 결과의 위치를 표시하도록 했습니다.

MainViewModel
```
class MainViewModel(context: Context) : ViewModel() {
    private val preferenceManager = MapApplication.prefs
    fun setLocation(latitude: Double? = null, longitude: Double? = null): LatLng? {
        return if (latitude != null && longitude != null) {
            LatLng.from(latitude, longitude)
        } else {
            val historyList = preferenceManager.getArrayList(Constants.SEARCH_HISTORY_KEY)
            if (historyList.isEmpty()) {
                null
            } else {
                val historyLongitude = historyList[0].document.x.toDouble()
                val historyLatitude = historyList[0].document.y.toDouble()
                LatLng.from(historyLatitude, historyLongitude)
            }
        }
    }
}
```
-> 위치를 정할 때, 넘어온 위도 경도 값이 있으면 그 값으로 위치를 반환하고, 그렇지 않은 경우 제일 최근 검색 장소의 위치를 반환하고, 저장된 검색어가 없는 경우에는 null을 반환합니다. 

MainActivity
```
    private fun setBottomSheet(name: String?, address: String?) {
        if (!name.isNullOrEmpty() && !address.isNullOrEmpty()) {
            mainViewBinding.place.text = name
            mainViewBinding.address.text = address
            mainViewBinding.mapBottomSheet.visibility = View.VISIBLE
        } else {
            mainViewBinding.mapBottomSheet.visibility = View.GONE
        }
    }
```
-> 서치액티비티에서 인텐트로 넘어온 값이 있으면 바텀 시트를 통해 그 정보를 보여줍니다

MainActiviy - MapView 부분
```
    override fun getPosition(): LatLng {
        return mainViewModel.setLocation(latitude, longitude) ?: super.getPosition()
    }
```
-> mainViewModel의 setLocation을 호출해 그 값을 할당하고, null인 경우에는 기존 super.getPosition()를 반환합니다.

### 💀어려웠던 부분
- 테스트 코드 작성 부분이 너무 어려웠습니다... 테스트 코드 작성하는 법을 잘 모르겠습니다. 작성하였으나 계속 통과하지 못하는 부분을 주석 처리 해두었습니다...

### ‼️피드백 받고 싶은 부분, 궁금한 부분
- MVVM에 어긋난 부분이 있는지 궁금합니다.

- 참고사항에서 말씀드렸듯이 맵 뷰를 하나만 만들어 사용하기 위해 서치뷰에서 검색 결과를 클릭하면 인텐트로 정보를 전달해주고 메인 액티비티로 넘어가게 했는데, 
이렇게 해도 되는지 궁금합니다. (뷰가 쌓였을 때 문제가 생길 수 있는 문제가 있는지, 또는 사용자가 불편함을 느끼게 만드는 기능지 궁금합니다.)

- 테스트 코드 개선할 부분이 있는지 알려주시면 감사드리겠습니다... 🥲🥲🥲🥲🥲🥲

**📷앱 사진**
<hr>
<img src ="https://github.com/user-attachments/assets/6552f6d4-185e-4187-9831-7fd28095fa87" width ="250">
<img src ="https://github.com/user-attachments/assets/f7b29070-0885-4ba8-9096-fc0b4998c929" width ="250">
<hr>

다시한번 늦게 제출하여 정말 죄송합니다... 코드리뷰 해주셔서 감사합니다!!

2024-07-21 04:25 UTC, omjoonkim requested changes
ViewModel 테스트 코드가 모두 작성이 되어있지 않은 것 같습니다. 확인 부탁드려요~!

2024-07-21 04:25 UTC, omjoonkim commented on app/src/androidTest/java/campus/tech/kakao/map/MainActivityTest.kt
> +        val editor = sharedPreferences.edit()
보통 테스트 코드 작성시 Given When Then 형태의 컨벤션을 사용합니다.
[링크](https://brunch.co.kr/@springboot/292)를 참고하여 코드를 수정해보세요.

2024-07-21 04:25 UTC, omjoonkim commented on app/src/main/java/campus/tech/kakao/map/MainActivity.kt
> +                val intent = Intent(this@MainActivity, ErrorActivity::class.java)
ErrorActivity로 이동한 뒤 백 버튼을 클릭 할 경우 이전 화면이 그대로 노출되게 됩니다. 
ErrorActivity에서 백버튼을 클릭했을 때 앱이 완전히 종료되도록 코드를 작성해보세요.

2024-07-21 04:25 UTC, omjoonkim commented on app/src/main/java/campus/tech/kakao/map/MainViewModel.kt
> +    private val preferenceManager = MapApplication.prefs
오브젝트를 사용할 경우 단위 테스팅 코드를 작성 할 때, 테스트 환경 설정에 어려움이 생길 수 있습니다.
생성자 주입을 통해 의존성을 관리 할  수 있도록 수정해보세요.

2024-07-21 04:26 UTC, omjoonkim commented on app/src/main/java/campus/tech/kakao/map/MainActivity.kt
> +            val intent = Intent(this@MainActivity, SearchActivity::class.java)
액티비티의 테스크 스택 관리가 필요해 보입니다. Intent의 여러 Flag 들을 활용하여 스택에 하나의 MainActivity 만 존재하도록 만들어보세요.

2024-07-23 05:11 UTC, sumintnals commented on app/src/main/java/campus/tech/kakao/map/MainActivity.kt
> +            val intent = Intent(this@MainActivity, SearchActivity::class.java)
네!! 고쳐보도록 하겠습니다!

2024-07-23 05:11 UTC, sumintnals commented on app/src/androidTest/java/campus/tech/kakao/map/MainActivityTest.kt
> +        val editor = sharedPreferences.edit()
감사합니다 수정하겠습니다!

2024-07-23 05:12 UTC, sumintnals commented on app/src/main/java/campus/tech/kakao/map/MainActivity.kt
> +                val intent = Intent(this@MainActivity, ErrorActivity::class.java)
넵!!

2024-07-23 05:12 UTC, sumintnals commented on app/src/main/java/campus/tech/kakao/map/MainViewModel.kt
> +    private val preferenceManager = MapApplication.prefs
넵!!! 수정하겠습니다

2024-07-23 10:28 UTC, sumintnals commented
코드리뷰 주신 것 반영하여 수정해보았습니다...!! Changes requested가 안 사라져서 이것저것 눌러보다가 re-request를 눌러버렸습니다 ㅠㅠㅠㅠ 혹시 잘못된 거라면 죄송합니다!!!!

2024-07-23 12:40 UTC, omjoonkim commented
re-request누르는 것 맞습니다. ㅎㅎ 잘하셨어요!

2024-07-23 12:46 UTC, omjoonkim commented on app/src/test/java/campus/tech/kakao/map/MainViewModelTest.kt
> +    class FakePreferenceManager(context: Context) : PreferenceManager(context) {
재사용 가능한 스텁 객체는 파일을 분리하여 재사용이 가능하게 만들면 좋을 것 같아요.

2024-07-23 12:46 UTC, omjoonkim approved these changes

2024-07-23 12:47 UTC, omjoonkim commented
2단계 과제 진행하시느라 고생하셨습니다. 주석처리된 코드와 테스트는 꼭 문제를 파악하여 해결해보세요~!

2024-07-23 12:47 UTC, merged